[build-system]
requires = [
    "setuptools>=50.3.0",
    "setuptools_scm[toml]>=4.1.2",
    "wheel>=0.35.1",
]

[project]
name = "pn532"
python = ">=3.7.3"
readme = "readme.md"

[tool.black]
line-length = 79
target-version = ["py37", "py38"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
exclude_lines = [
    "raise NotImplementedError()",
    "pragma: nocover",
    "if __name__ == .__main__.:",
]
precision = 2
show_missing = true

[tool.coverage.run]
branch = true
source = ["pn532", "test"]
parallel = true

[tool.pylint.basic]
good-names = '''i,logger'''

[tool.pylint.message_control]
disable = '''duplicate-code,C0330'''

[tool.pylint.miscellaneous]
notes = '''FIXME,XXX'''

[tool.pylint.similarities]
min-similarity-lines = 4
ignore-comments = "yes"
ignore-docstrings = "yes"
ignore-imports = "yes"

[tool.pytest.ini_options]
addopts = "-ra --cov=asah --cov-report=term-missing --strict --ignore=.eggs --tb=short"
testpaths = ["test"]
norecursedirs = ".env .git build dist"
python_files = "test.py tests.py test_*.py *_test.py"

[tool.setuptools_scm]
local_scheme = "dirty-tag"
